name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: dfinity/setup-mops@v1
        with:
          mops-version: 1

      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test