name: Build CLI and print hash

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Docker
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
      - name: Build using Docker
        run: |
          # MOPS_VERSION=$(cd cli && npm pkg get version | tr -d \")
          # echo MOPS_VERSION=$MOPS_VERSION
          # if [ -z "$MOPS_VERSION" ]; then
          #   echo "MOPS_VERSION is empty"
          #   exit 1
          # fi
          MOPS_VERSION=0.0.0
          cd cli
          docker build . --build-arg COMMIT_HASH=${{ github.sha }} --build-arg MOPS_VERSION=$MOPS_VERSION -t mops
          OUTPUT=$(docker run --rm mops || echo ".")
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
