name: CLI bundle

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20, 24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}, node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: 1.2.17
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: cd cli && npm i

      - name: Prepare
        run: cd cli && npm run prepare

      - name: Bundle
        run: cd cli && npm run bundle

      - name: Check local bundle
        run: node ./cli/bundle/cli.js -v

      - name: Install bundle globally
        run: npm i -g ./cli/bundle/cli.tgz

      - name: Check global bundle
        run: mops -v

      - run: mops format
