name: mops test with ZenVoich/setup-mops

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ZenVoich/setup-mops

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: dfinity/setup-dfx@main
      - uses: ZenVoich/setup-mops@3e94e453352269b34137b5ce49f09a8df81bed7d # v1.4.1
        with:
          mops-version: 1.0.0
      - name: Run tests
        run: mops test
