name: mops test with dfinity/setup-mops

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with dfinity/setup-mops

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: dfinity/setup-dfx@main
      - uses: dfinity/setup-mops@v1
        with:
          mops-version: 1.0.0
      - name: Run tests
        run: mops test
